version: '3.8'

networks:
  local-chatbot:
    name: local-chatbot

services:
  natti-chat-bot:
    container_name: natti-chat-bot
    #image: "eveloth/natti-chat-bot:${BOT_TAG}"
    build: ./src/NattiChatBot
    restart: unless-stopped
    ports:
      - "${BOT_PORT}:80"
    depends_on:
      - "redis-db"
    networks:
      - local-chatbot
    env_file:
      - .env
      - bot-config.env

  redis-db:
    container_name: redis
    image: redis:7.0
    command: >
      --requirepass ${Redis__Password}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - /opt/natti-chat-bot/redis:/data
    networks:
      - local-chatbot

